# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  redis-node-0:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
      - ./rootfs/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh:/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    entrypoint: ["/bin/bash", "/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh"]
    command: "/opt/bitnami/scripts/redis-cluster/run.sh"

  redis-node-1:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
      - ./rootfs/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh:/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    entrypoint: ["/bin/bash", "/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh"]
    command: "/opt/bitnami/scripts/redis-cluster/run.sh"

  redis-node-2:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
      - ./rootfs/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh:/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    entrypoint: ["/bin/bash", "/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh"]
    command: "/opt/bitnami/scripts/redis-cluster/run.sh"

  redis-node-3:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
      - ./rootfs/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh:/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    entrypoint: ["/bin/bash", "/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh"]
    command: "/opt/bitnami/scripts/redis-cluster/run.sh"

  redis-node-4:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
      - ./rootfs/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh:/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
    entrypoint: ["/bin/bash", "/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh"]
    command: "/opt/bitnami/scripts/redis-cluster/run.sh"

  redis-node-5:
    image: my-redis-with-modules:latest
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
      - ./rootfs/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh:/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
    entrypoint: ["/bin/bash", "/opt/bitnami/scripts/redis-cluster/entrypoint-custom.sh"]
    command: "/opt/bitnami/scripts/redis-cluster/run.sh"

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local